language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
script:
  - mvn test
  - "./jackson-it.sh"
  - mvn -B -DdryRun=true release:prepare -Darguments="-Dgpg.skip=true -DskipTests"
  - mvn -B -DdryRun=true release:perform -Darguments="-Dgpg.skip=true -DskipTests"
